---
- hosts: localhost
  vars:
    homebrew_installed_packages:
      - git
      - nvim
      - node
      - terraform
      - python
      - jq
      - go
    homebrew_cask_apps:
      - visual-studio-code
      - brave-browser
      - discord
  tasks:
    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
      loop: "{{ homebrew_installed_packages }}"
    - name: Install Homebrew casks
      homebrew_cask:
        name: "{{ item }}"
      loop: "{{ homebrew_cask_apps }}"
    - name: Generate SSH keypair
      openssh_keypair:
        path: ~/.ssh/id_ecdsa
        type: ecdsa
        size: 521
    - name: Copy zshrc file
      copy:
        src: files/zshrc
        dest: ~/.zshrc
        owner: jaredready
        group: staff
        mode: 0644
    - name: Copy init.vim file
      copy:
        src: files/init.vim
        dest: ~/.config/nvim/init.vim
        owner: jaredready
        group: staff
        mode: 0644
    - name: Install AWS CLI
      become: yes
      command:
        creates: /usr/local/bin/aws
        cmd: "curl 'https://awscli.amazonaws.com/AWSCLIV2.pkg' -o 'AWSCLIV2.pkg' && installer -pkg AWSCLIV2.pkg -target /"
    - name: Install aws-cdk
      npm:
        name: aws-cdk
        global: yes
    - name: Install typescript
      npm:
        name: typescript
        global: yes
    - name: Install pipenv
      pip:
        name: pipenv
        extra_args: --user
    - name: Install pylint
      pip:
        name: pylint
        extra_args: --user

